baseURL = "https://campsynthesis.neuromoda.me"
title = "Camp Synthesis"
theme = "reveal-hugo"
enableEmoji = true

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[languages]
  [languages.ja]
    languageName = "日本語"
    languageCode = "ja"
    weight = 1
    title = "キャンプ・シンセシス"
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    title = "Camp Synthesis"
